server:
  port: 8080
  servlet:
    context-path: /liangzhicheng

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/basic_framework?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  redis:
    host: 127.0.0.1
    port: 6379
#    password: 011556ffd7b644589e796a368a122d57

mvc:
  static:
    dirs: /css,/js,/upload
    prefix: http://127.0.0.1:${server.port}${server.servlet.context-path}


